{
  config,
  lib,
  pkgs,
  ...
}: {
  imports = [
    ./general.nix
    ./keybinds.nix
    ./env.nix
    ./windowrules.nix
  ];

  stylix.targets.hyprland.enable = true;

  # hyprland
  wayland.windowManager.hyprland = {
    enable = true;
    systemd.enable = false;
    configType = "lua";
    package = null;
    portalPackage = null;
  };

  home.sessionVariables.HYPRLAND_CONFIG = "${config.xdg.configHome}/hypr/hyprland.lua";

  home.activation.removeAutogeneratedHyprlandConf = lib.hm.dag.entryAfter ["writeBoundary"] ''
    conf="${config.xdg.configHome}/hypr/hyprland.conf"

    if [ -L "$conf" ]; then
      target="$(${pkgs.coreutils}/bin/readlink -f "$conf" || true)"

      case "$target" in
        /nix/store/*-home-manager-files/.config/hypr/hyprland.conf)
          run ${pkgs.coreutils}/bin/rm -f "$conf"
          ;;
        /nix/store/*)
          if [ -f "$target" ] \
            && ${pkgs.gnugrep}/bin/grep -q '^autogenerated = 1$' "$target" \
            && ${pkgs.gnugrep}/bin/grep -q 'This config is a STUB' "$target"; then
            run ${pkgs.coreutils}/bin/rm -f "$conf"
          fi
          ;;
      esac
    elif [ -f "$conf" ] \
      && ${pkgs.gnugrep}/bin/grep -q '^autogenerated = 1$' "$conf" \
      && ${pkgs.gnugrep}/bin/grep -q 'This config is a STUB' "$conf"; then
        run ${pkgs.coreutils}/bin/rm -f "$conf"
    fi
  '';
}
