{
  config,
  lib,
  pkgs,
  ...
}: {
  options.dotnix.hyprland.autostart = {
    openrgb = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Start OpenRGB with the Hyprland session.";
    };

    noctalia = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Start Noctalia with the Hyprland session.";
    };

    spotify = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Start Spotify with the Hyprland session.";
    };

    obsidian = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Start Obsidian with the Hyprland session.";
    };

    startupVolume = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = "1";
      description = "Volume value passed to wpctl at Hyprland startup, or null to leave volume unchanged.";
    };
  };

  imports = [
    ./general.nix
    ./keybinds.nix
    ./env.nix
    ./windowrules.nix
  ];

  config = {
    stylix.targets.hyprland.enable = true;

    # hyprland
    wayland.windowManager.hyprland = {
      enable = true;
      systemd.enable = false;
      configType = "lua";
      package = null;
      portalPackage = null;
    };

    home.sessionVariables.HYPRLAND_CONFIG = "${config.xdg.configHome}/hypr/hyprland.lua";

    home.activation.removeAutogeneratedHyprlandConf = lib.hm.dag.entryAfter ["writeBoundary"] ''
      conf="${config.xdg.configHome}/hypr/hyprland.conf"

      if [ -L "$conf" ]; then
        target="$(${pkgs.coreutils}/bin/readlink -f "$conf" || true)"

        case "$target" in
          /nix/store/*-home-manager-files/.config/hypr/hyprland.conf)
            run ${pkgs.coreutils}/bin/rm -f "$conf"
            ;;
          /nix/store/*)
            if [ -f "$target" ] \
              && ${pkgs.gnugrep}/bin/grep -q '^autogenerated = 1$' "$target" \
              && ${pkgs.gnugrep}/bin/grep -q 'This config is a STUB' "$target"; then
              run ${pkgs.coreutils}/bin/rm -f "$conf"
            fi
            ;;
        esac
      elif [ -f "$conf" ] \
        && ${pkgs.gnugrep}/bin/grep -q '^autogenerated = 1$' "$conf" \
        && ${pkgs.gnugrep}/bin/grep -q 'This config is a STUB' "$conf"; then
          run ${pkgs.coreutils}/bin/rm -f "$conf"
      fi
    '';
  };
}
